buildscript {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
    }
    dependencies {
        classpath "net.fabricmc:fabric-loom:${loom_version}"
    }
}

apply plugin: 'fabric-loom'

rootProject.ext.loadModProperties(project, 'TokorotenSlime')

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    compileOnly "net.fabricmc:sponge-mixin:0.12.5+mixin.0.8.5"

    implementation project(path: ':TokorotenSlime:common', configuration: 'namedElements')
}

rootProject.ext.configureFabricModule(project, ':TokorotenSlime:common')
