plugins {
    id 'idea'
    id 'net.neoforged.gradle.userdev' version "${neogradle_version}" apply false
}

allprojects {
    repositories {
        mavenCentral()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
    }
}

subprojects {
    plugins.withId('java') {
        java {
            sourceCompatibility = JavaVersion.VERSION_25
            targetCompatibility = JavaVersion.VERSION_25
            toolchain.languageVersion = JavaLanguageVersion.of(25)
        }
    }
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    pluginManager.withPlugin('net.neoforged.gradle.userdev') {
        dependencies {
            implementation "net.neoforged:neoforge:${project.neo_version}"
        }
    }

    pluginManager.withPlugin('maven-publish') {
        afterEvaluate {
            publishing {
                publications {
                    register('mavenJava', MavenPublication) {
                        artifact tasks.named('jar')
                    }
                }
                repositories {
                    maven {
                        url "file://${project.projectDir}/mcmodsrepo"
                    }
                }
            }
        }
    }
}

ext.loadModProperties = { Project project, String modDirName ->
    def modProps = new Properties()
    file("${rootDir}/${modDirName}/gradle.properties").withInputStream { modProps.load(it) }
    modProps.each { key, value -> project.ext[key] = value }
    project.version = modProps.getProperty('mod_version')
    project.group = modProps.getProperty('mod_group_id')
}

ext.applyLoomMinecraft = { Project project ->
    project.dependencies {
        minecraft "com.mojang:minecraft:${project.minecraft_version}"
    }
}

ext.configureCommonModule = { Project project ->
    rootProject.ext.applyLoomMinecraft(project)

    project.dependencies {
        compileOnly "net.fabricmc:fabric-loader:${project.loader_version}"
    }
}

ext.configureNeoForgeRuns = { Project project, Map<String, List<SourceSet>> extraModSources ->
    project.sourceSets.main.runs.modIdentifier = project.mod_id

    project.runs {
        configureEach { run ->
            run.systemProperty 'forge.logging.markers', 'REGISTRIES'
            run.systemProperty 'forge.logging.console.level', 'debug'

            extraModSources.each { modId, sourceSetList ->
                sourceSetList.each { run.modSources.add(modId, it) }
            }
        }

        client { }

        server {
            argument '--nogui'
        }
    }
}

ext.configureNeoForgeModule = { Project project, String commonProjectPath ->
    project.base {
        archivesName = "${project.mod_id}-neoforge-mc${project.minecraft_version}"
    }

    project.sourceSets.main.resources {
        srcDir project.project(commonProjectPath).file('src/main/resources')
    }

    project.tasks.named('processResources', ProcessResources).configure {
        var replaceProperties = [
                minecraft_version: project.minecraft_version, minecraft_version_range: project.minecraft_version_range,
                neo_version: project.neo_version,
                mod_id: project.mod_id, mod_name: project.mod_name, mod_license: project.mod_license,
                mod_version: project.mod_version, mod_authors: project.mod_authors, mod_description: project.mod_description,
        ]

        if (project.hasProperty('tokorotenslime_version')) {
            replaceProperties.tokorotenslime_version = project.tokorotenslime_version
        }
        inputs.properties replaceProperties

        filesMatching(['META-INF/neoforge.mods.toml']) {
            expand replaceProperties
        }
    }

    project.tasks.named('jar', Jar).configure {
        from(project.project(commonProjectPath).sourceSets.main.output)
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE

        manifest {
            attributes([
                    'Specification-Title'     : project.mod_id,
                    'Specification-Vendor'    : project.mod_authors,
                    'Specification-Version'   : '1',
                    'Implementation-Title'    : project.name,
                    'Implementation-Version'  : project.version,
                    'Implementation-Vendor'   : project.mod_authors,
                    'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
            ])
        }
    }
}

ext.configureFabricModule = { Project project, String commonProjectPath ->
    rootProject.ext.applyLoomMinecraft(project)

    project.base {
        archivesName = "${project.mod_id}-fabric-mc${project.minecraft_version}"
    }

    project.sourceSets.main.resources {
        srcDir project.project(commonProjectPath).file('src/main/resources')
    }

    project.processResources {
        var replaceProperties = [
                mod_id: project.mod_id, mod_name: project.mod_name, mod_version: project.mod_version,
                mod_description: project.mod_description, mod_authors: project.mod_authors,
                minecraft_version: project.minecraft_version, fabric_api_version: project.fabric_api_version,
                loader_version: project.loader_version,
        ]

        if (project.hasProperty('tokorotenslime_version')) {
            replaceProperties.tokorotenslime_version = project.tokorotenslime_version
        }
        inputs.properties replaceProperties

        filesMatching(['fabric.mod.json']) {
            expand replaceProperties
        }
    }

    project.jar {
        from(project.project(commonProjectPath).sourceSets.main.output)
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
}
