# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false

org.gradle.configuration-cache=false

## ===== Minecraft / 共通バージョン情報 =====
minecraft_version=26.1
minecraft_version_range=[26.1,26.2)

## ===== Fabric Properties =====
loader_version=0.18.4
loom_version=1.15.5
fabric_api_version=0.144.0+26.1

## ===== NeoForge Properties =====
neo_version=26.1.0.19-beta
neogradle_version=7.1.25
