plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

rootProject.ext.loadModProperties(project, 'TokorotenSlime')

rootProject.ext.configureForgeMinecraft(project) {
    "${mod_id}" {
        source sourceSets.main
        source project(':TokorotenSlime:common').sourceSets.main
    }
}

dependencies {
    implementation project(':TokorotenSlime:common')
}

rootProject.ext.configureForgeModule(project, ':TokorotenSlime:common')
