plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev'
}

rootProject.ext.loadModProperties(project, 'TokorotenSlime')

rootProject.ext.configureNeoForgeRuns(project, [
        (mod_id): [project(':TokorotenSlime:common').sourceSets.main]
])

dependencies {
    implementation(project(':TokorotenSlime:common')) { transitive = false }
}

rootProject.ext.configureNeoForgeModule(project, ':TokorotenSlime:common')
